name: 🐛 Bug Report
description: Create a report to help us improve the Agentic Startup Studio Boilerplate
title: "[Bug]: "
labels: ["bug", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to fill out this bug report! Please provide as much detail as possible to help us reproduce and fix the issue.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have read the [contributing guidelines](../../CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have tested this with the latest version
          required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is
      placeholder: Describe the bug in detail...
    validations:
      required: true

  - type: textarea
    id: reproduce
    attributes:
      label: Steps to Reproduce
      description: Steps to reproduce the behavior
      placeholder: |
        1. Go to '...'
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen
      placeholder: What should have happened?
    validations:
      required: true

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: A clear and concise description of what actually happened
      placeholder: What actually happened?
    validations:
      required: true

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: Please provide information about your environment
      value: |
        - OS: [e.g. Ubuntu 20.04, macOS 12.3, Windows 11]
        - Python Version: [e.g. 3.11.2]
        - Node.js Version: [e.g. 18.15.0]
        - Docker Version: [e.g. 23.0.1]
        - Browser: [e.g. Chrome 110.0, Firefox 109.0] (if applicable)
        - Template Version: [e.g. v0.2.0]
    validations:
      required: true

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected by this bug?
      options:
        - Frontend (React)
        - Backend (FastAPI)
        - AI/ML (CrewAI)
        - Database (PostgreSQL)
        - Cache (Redis)
        - Authentication (Keycloak)
        - Infrastructure (Docker/K8s)
        - CI/CD (GitHub Actions)
        - Documentation
        - Other
    validations:
      required: true

  - type: dropdown
    id: severity
    attributes:
      label: Severity
      description: How severe is this bug?
      options:
        - Critical (System unusable)
        - High (Major functionality broken)
        - Medium (Some functionality affected)
        - Low (Minor issue)
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs and Stack Traces
      description: Please paste any relevant logs, error messages, or stack traces
      render: shell
      placeholder: Paste logs here...

  - type: textarea
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem
      placeholder: You can drag and drop images here...

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context about the problem here
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to fixing this issue?
      options:
        - label: I would like to work on fixing this bug
          required: false