name: ✨ Feature Request
description: Suggest a new feature or enhancement for the Agentic Startup Studio Boilerplate
title: "[Feature]: "
labels: ["enhancement", "triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: checkboxes
    id: preflight
    attributes:
      label: Pre-flight checklist
      description: Please ensure you've completed these steps before submitting
      options:
        - label: I have read the [contributing guidelines](../../CONTRIBUTING.md)
          required: true
        - label: I have searched existing issues to avoid duplicates
          required: true
        - label: I have checked the [roadmap](../../docs/ROADMAP.md) for planned features
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the pain point?
      placeholder: |
        As a [user type], I want [goal] so that [reason].
        
        Currently, [describe the problem or limitation]...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented
      placeholder: |
        I would like to see [describe your proposed solution]...
        
        This would work by [explain how it would work]...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternative Solutions
      description: Describe any alternative solutions or features you've considered
      placeholder: |
        I've also considered [alternative 1] but [reason why it's not ideal]...
        
        Another option would be [alternative 2]...

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component would this feature primarily affect?
      options:
        - Frontend (React)
        - Backend (FastAPI)
        - AI/ML (CrewAI)
        - Database (PostgreSQL)
        - Cache (Redis)
        - Authentication (Keycloak)
        - Infrastructure (Docker/K8s)
        - CI/CD (GitHub Actions)
        - Documentation
        - Cookiecutter Template
        - Development Tools
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - High (Critical for my use case)
        - Medium (Would be very helpful)
        - Low (Nice to have)
    validations:
      required: true

  - type: dropdown
    id: user_type
    attributes:
      label: User Type
      description: Who would primarily benefit from this feature?
      options:
        - Startup Founders
        - Developers
        - DevOps Engineers
        - AI/ML Engineers
        - Product Managers
        - All Users
        - Other
    validations:
      required: true

  - type: textarea
    id: use_cases
    attributes:
      label: Use Cases
      description: Provide specific use cases or examples of how this feature would be used
      placeholder: |
        Use Case 1: [Describe scenario]
        - User does [action]
        - System responds with [behavior]
        - User achieves [outcome]
        
        Use Case 2: [Describe another scenario]...

  - type: textarea
    id: acceptance_criteria
    attributes:
      label: Acceptance Criteria
      description: What would make this feature complete? How would you test it?
      placeholder: |
        - [ ] Feature should do X
        - [ ] When Y happens, system should Z
        - [ ] Feature should handle edge case A
        - [ ] Performance should be within B seconds
        - [ ] Feature should be accessible via C

  - type: textarea
    id: technical_considerations
    attributes:
      label: Technical Considerations
      description: Any technical aspects, dependencies, or constraints to consider?
      placeholder: |
        - Dependencies: [list any new dependencies]
        - Performance impact: [describe potential impact]
        - Security considerations: [any security aspects]
        - Backward compatibility: [compatibility concerns]
        - Integration points: [how it integrates with existing features]

  - type: textarea
    id: mockups
    attributes:
      label: Mockups/Wireframes
      description: If this is a UI feature, please provide mockups, wireframes, or sketches
      placeholder: You can drag and drop images here...

  - type: textarea
    id: references
    attributes:
      label: References
      description: Links to similar features in other tools, documentation, or resources
      placeholder: |
        - Similar feature in X: [URL]
        - Documentation: [URL]
        - Related discussion: [URL]

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or information about the feature request
      placeholder: Any additional information that might be helpful...

  - type: checkboxes
    id: contribution
    attributes:
      label: Contribution
      description: Would you like to contribute to implementing this feature?
      options:
        - label: I would like to work on implementing this feature
          required: false
        - label: I can provide design/UX input
          required: false
        - label: I can help with testing
          required: false