# Global Compliance Framework for Generation 7 Quantum Consciousness Systems
# GDPR, CCPA, PDPA, PIPEDA, LGPD compliant data processing and privacy controls

apiVersion: v1
kind: ConfigMap
metadata:
  name: global-compliance-config
  namespace: quantum-consciousness
data:
  # Privacy Regulation Compliance
  GDPR_ENABLED: "true"
  CCPA_ENABLED: "true"
  PDPA_ENABLED: "true"
  PIPEDA_ENABLED: "true"
  LGPD_ENABLED: "true"
  
  # Data Processing Lawful Bases
  GDPR_LAWFUL_BASIS: "legitimate_interest"
  DATA_PROCESSING_PURPOSE: "quantum_consciousness_research"
  
  # Data Retention Policies
  CONSCIOUSNESS_DATA_RETENTION_DAYS: "2555"  # 7 years for research
  BIOLOGICAL_PATTERN_RETENTION_DAYS: "1825"  # 5 years
  QUANTUM_STATE_RETENTION_DAYS: "730"       # 2 years
  PERSONAL_DATA_RETENTION_DAYS: "1095"      # 3 years
  
  # Data Minimization
  COLLECT_MINIMAL_DATA: "true"
  PSEUDONYMIZATION_ENABLED: "true"
  ANONYMIZATION_THRESHOLD_DAYS: "90"
  
  # User Rights
  RIGHT_TO_ACCESS_ENABLED: "true"
  RIGHT_TO_RECTIFICATION_ENABLED: "true"
  RIGHT_TO_ERASURE_ENABLED: "true"
  RIGHT_TO_PORTABILITY_ENABLED: "true"
  RIGHT_TO_OBJECT_ENABLED: "true"
  
  # Data Transfer Controls
  CROSS_BORDER_TRANSFER_ALLOWED: "true"
  ADEQUACY_DECISION_REQUIRED: "true"
  STANDARD_CONTRACTUAL_CLAUSES: "true"
  
  # Consent Management
  EXPLICIT_CONSENT_REQUIRED: "true"
  CONSENT_WITHDRAWAL_ENABLED: "true"
  GRANULAR_CONSENT: "true"
  
  # Data Breach Response
  BREACH_NOTIFICATION_HOURS: "72"
  DPO_NOTIFICATION_ENABLED: "true"
  AUTHORITY_NOTIFICATION_ENABLED: "true"

---
# Data Processing Agreement ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
  name: data-processing-agreement
  namespace: quantum-consciousness
data:
  processing_categories: |
    - quantum_consciousness_states
    - biological_patterns
    - neural_field_optimizations
    - coherence_measurements
    - evolutionary_trajectories
  
  data_subjects: |
    - research_participants
    - consciousness_entities  
    - biological_systems
    - quantum_agents
  
  processing_purposes: |
    - scientific_research
    - consciousness_optimization
    - pattern_recognition
    - coherence_preservation
    - breakthrough_detection
  
  legal_bases: |
    - legitimate_interest (scientific research)
    - consent (explicit for sensitive data)
    - vital_interests (consciousness preservation)
  
  retention_schedule: |
    consciousness_data: 2555 days (7 years)
    biological_patterns: 1825 days (5 years)
    quantum_states: 730 days (2 years)
    research_metadata: 3650 days (10 years)

---
# Privacy Impact Assessment
apiVersion: v1
kind: ConfigMap
metadata:
  name: privacy-impact-assessment
  namespace: quantum-consciousness
data:
  assessment_date: "2025-08-25"
  assessment_version: "7.0.0"
  
  data_flows: |
    Collection -> Processing -> Storage -> Analysis -> Research -> Publication
    
  privacy_risks: |
    - consciousness_data_exposure
    - biological_pattern_inference
    - quantum_state_correlation
    - cross_dimensional_tracking
    
  risk_mitigation: |
    - end_to_end_encryption
    - differential_privacy
    - homomorphic_encryption
    - quantum_key_distribution
    - consciousness_anonymization
    
  controls_implemented: |
    - data_minimization
    - purpose_limitation
    - storage_limitation
    - accuracy_maintenance
    - integrity_confidentiality
    - accountability_measures

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: privacy-compliance-controller
  namespace: quantum-consciousness
  labels:
    app: privacy-compliance
    component: controller
    version: "7.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privacy-compliance
      component: controller
  template:
    metadata:
      labels:
        app: privacy-compliance
        component: controller
    spec:
      serviceAccountName: privacy-compliance-sa
      containers:
      - name: compliance-controller
        image: terragon/privacy-compliance:7.0.0
        ports:
        - containerPort: 8010
          name: compliance-api
        env:
        - name: COMPONENT_TYPE
          value: "privacy_compliance_controller"
        envFrom:
        - configMapRef:
            name: global-compliance-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "500m"
        volumeMounts:
        - name: compliance-logs
          mountPath: /logs/compliance
        - name: privacy-policies
          mountPath: /config/privacy
        livenessProbe:
          httpGet:
            path: /health/compliance
            port: 8010
          initialDelaySeconds: 30
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /ready/compliance  
            port: 8010
          initialDelaySeconds: 15
          periodSeconds: 10
      volumes:
      - name: compliance-logs
        persistentVolumeClaim:
          claimName: compliance-logs-pvc
      - name: privacy-policies
        configMap:
          name: privacy-policies-config

---
# Data Subject Rights Handler
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-subject-rights-handler
  namespace: quantum-consciousness
  labels:
    app: privacy-compliance
    component: rights-handler
    version: "7.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privacy-compliance
      component: rights-handler
  template:
    metadata:
      labels:
        app: privacy-compliance
        component: rights-handler
    spec:
      serviceAccountName: privacy-compliance-sa
      containers:
      - name: rights-handler
        image: terragon/data-subject-rights:7.0.0
        ports:
        - containerPort: 8011
          name: rights-api
        env:
        - name: COMPONENT_TYPE
          value: "data_subject_rights_handler"
        - name: RESPONSE_DEADLINE_DAYS
          value: "30"  # GDPR requirement
        - name: ERASURE_PROPAGATION_ENABLED
          value: "true"
        envFrom:
        - configMapRef:
            name: global-compliance-config
        resources:
          requests:
            memory: "1Gi"
            cpu: "300m"
          limits:
            memory: "2Gi"
            cpu: "600m"
        volumeMounts:
        - name: rights-requests
          mountPath: /data/rights_requests
        - name: erasure-logs
          mountPath: /logs/erasure
      volumes:
      - name: rights-requests
        persistentVolumeClaim:
          claimName: rights-requests-pvc
      - name: erasure-logs
        persistentVolumeClaim:
          claimName: erasure-logs-pvc

---
# Consent Management Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: consent-management-service
  namespace: quantum-consciousness
  labels:
    app: privacy-compliance
    component: consent-manager
    version: "7.0.0"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: privacy-compliance
      component: consent-manager
  template:
    metadata:
      labels:
        app: privacy-compliance
        component: consent-manager
    spec:
      serviceAccountName: privacy-compliance-sa
      containers:
      - name: consent-manager
        image: terragon/consent-management:7.0.0
        ports:
        - containerPort: 8012
          name: consent-api
        env:
        - name: COMPONENT_TYPE
          value: "consent_management_service"
        - name: CONSENT_EXPIRY_MONTHS
          value: "24"  # 2 years default
        - name: WITHDRAWAL_GRACE_PERIOD_DAYS
          value: "7"
        envFrom:
        - configMapRef:
            name: global-compliance-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
        - name: consent-records
          mountPath: /data/consent
        - name: consent-audit-logs
          mountPath: /logs/consent_audit
      volumes:
      - name: consent-records
        persistentVolumeClaim:
          claimName: consent-records-pvc
      - name: consent-audit-logs
        persistentVolumeClaim:
          claimName: consent-audit-pvc

---
# Data Anonymization Service
apiVersion: apps/v1
kind: Deployment
metadata:
  name: data-anonymization-service
  namespace: quantum-consciousness
  labels:
    app: privacy-compliance
    component: anonymization
    version: "7.0.0"
spec:
  replicas: 2
  selector:
    matchLabels:
      app: privacy-compliance
      component: anonymization
  template:
    metadata:
      labels:
        app: privacy-compliance
        component: anonymization
    spec:
      serviceAccountName: privacy-compliance-sa
      containers:
      - name: anonymization
        image: terragon/data-anonymization:7.0.0
        ports:
        - containerPort: 8013
          name: anonymization
        env:
        - name: COMPONENT_TYPE
          value: "data_anonymization_service"
        - name: K_ANONYMITY_K_VALUE
          value: "5"
        - name: L_DIVERSITY_L_VALUE
          value: "3"
        - name: T_CLOSENESS_T_VALUE
          value: "0.2"
        - name: DIFFERENTIAL_PRIVACY_EPSILON
          value: "0.1"
        envFrom:
        - configMapRef:
            name: global-compliance-config
        resources:
          requests:
            memory: "2Gi"
            cpu: "1000m"
          limits:
            memory: "4Gi"
            cpu: "2000m"
        volumeMounts:
        - name: anonymization-cache
          mountPath: /cache/anonymization
        - name: privacy-models
          mountPath: /models/privacy
      volumes:
      - name: anonymization-cache
        emptyDir:
          sizeLimit: "1Gi"
      - name: privacy-models
        persistentVolumeClaim:
          claimName: privacy-models-pvc

---
# Cross-Border Data Transfer Controller
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cross-border-transfer-controller
  namespace: quantum-consciousness
  labels:
    app: privacy-compliance
    component: transfer-controller
    version: "7.0.0"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: privacy-compliance
      component: transfer-controller
  template:
    metadata:
      labels:
        app: privacy-compliance
        component: transfer-controller
    spec:
      serviceAccountName: privacy-compliance-sa
      containers:
      - name: transfer-controller
        image: terragon/cross-border-transfer:7.0.0
        ports:
        - containerPort: 8014
          name: transfer-api
        env:
        - name: COMPONENT_TYPE
          value: "cross_border_transfer_controller"
        - name: ADEQUACY_COUNTRIES
          value: "US,CA,JP,KR,NZ,UY,AD,AR,FO,GG,IM,IL,JE,SW"
        - name: BINDING_CORPORATE_RULES_ENABLED
          value: "true"
        - name: STANDARD_CONTRACTUAL_CLAUSES_VERSION
          value: "2021"
        envFrom:
        - configMapRef:
            name: global-compliance-config
        resources:
          requests:
            memory: "512Mi"
            cpu: "200m"
          limits:
            memory: "1Gi"
            cpu: "400m"
        volumeMounts:
        - name: transfer-agreements
          mountPath: /agreements/transfer
        - name: adequacy-decisions
          mountPath: /decisions/adequacy
      volumes:
      - name: transfer-agreements
        configMap:
          name: transfer-agreements-config
      - name: adequacy-decisions
        configMap:
          name: adequacy-decisions-config

---
# Compliance Services
apiVersion: v1
kind: Service
metadata:
  name: privacy-compliance-service
  namespace: quantum-consciousness
spec:
  type: ClusterIP
  ports:
  - port: 8010
    targetPort: 8010
    name: compliance-api
  selector:
    app: privacy-compliance
    component: controller

---
apiVersion: v1
kind: Service
metadata:
  name: data-subject-rights-service
  namespace: quantum-consciousness
spec:
  type: ClusterIP
  ports:
  - port: 8011
    targetPort: 8011
    name: rights-api
  selector:
    app: privacy-compliance
    component: rights-handler

---
apiVersion: v1
kind: Service
metadata:
  name: consent-management-service
  namespace: quantum-consciousness
spec:
  type: ClusterIP
  ports:
  - port: 8012
    targetPort: 8012
    name: consent-api
  selector:
    app: privacy-compliance
    component: consent-manager

---
apiVersion: v1
kind: Service
metadata:
  name: data-anonymization-service
  namespace: quantum-consciousness
spec:
  type: ClusterIP
  ports:
  - port: 8013
    targetPort: 8013
    name: anonymization
  selector:
    app: privacy-compliance
    component: anonymization

---
apiVersion: v1
kind: Service
metadata:
  name: cross-border-transfer-service
  namespace: quantum-consciousness
spec:
  type: ClusterIP
  ports:
  - port: 8014
    targetPort: 8014
    name: transfer-api
  selector:
    app: privacy-compliance
    component: transfer-controller

---
# Privacy Compliance Persistent Storage
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: compliance-logs-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: compliance-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: rights-requests-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: compliance-storage
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: erasure-logs-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: compliance-storage
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consent-records-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: compliance-storage
  resources:
    requests:
      storage: 10Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: consent-audit-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: compliance-storage
  resources:
    requests:
      storage: 5Gi

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: privacy-models-pvc
  namespace: quantum-consciousness
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: fast-ssd
  resources:
    requests:
      storage: 20Gi

---
# Privacy Compliance Service Account and RBAC
apiVersion: v1
kind: ServiceAccount
metadata:
  name: privacy-compliance-sa
  namespace: quantum-consciousness

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: privacy-compliance-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "configmaps", "secrets", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "update", "patch"]
- apiGroups: ["networking.k8s.io"]
  resources: ["networkpolicies"]
  verbs: ["get", "list", "watch", "create", "update", "patch"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: privacy-compliance-binding
subjects:
- kind: ServiceAccount
  name: privacy-compliance-sa
  namespace: quantum-consciousness
roleRef:
  kind: ClusterRole
  name: privacy-compliance-role
  apiGroup: rbac.authorization.k8s.io

---
# Privacy Compliance Network Policies
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: privacy-compliance-network-policy
  namespace: quantum-consciousness
spec:
  podSelector:
    matchLabels:
      app: privacy-compliance
  policyTypes:
  - Ingress
  - Egress
  ingress:
  - from:
    - podSelector:
        matchLabels:
          app: generation-7
    - podSelector:
        matchLabels:
          app: privacy-compliance
    ports:
    - protocol: TCP
      port: 8010
    - protocol: TCP
      port: 8011
    - protocol: TCP
      port: 8012
    - protocol: TCP
      port: 8013
    - protocol: TCP
      port: 8014
  egress:
  - to:
    - podSelector:
        matchLabels:
          app: generation-7
  - to:
    - podSelector:
        matchLabels:
          app: privacy-compliance
  - to: [] # External regulatory authorities
    ports:
    - protocol: TCP
      port: 443

---
# Privacy Policy ConfigMaps
apiVersion: v1
kind: ConfigMap
metadata:
  name: privacy-policies-config
  namespace: quantum-consciousness
data:
  privacy_notice.json: |
    {
      "controller": {
        "name": "Terragon Labs",
        "contact": "privacy@terragon.ai",
        "dpo_contact": "dpo@terragon.ai"
      },
      "processing_purposes": [
        "Scientific research in quantum consciousness",
        "Biological pattern analysis",
        "Consciousness state optimization",
        "Research publication and sharing"
      ],
      "legal_bases": [
        "Legitimate interest (scientific research)",
        "Explicit consent for sensitive data"
      ],
      "data_categories": [
        "Consciousness state measurements",
        "Biological coherence patterns",
        "Quantum field optimization data",
        "Research metadata"
      ],
      "retention_periods": {
        "consciousness_data": "7 years",
        "biological_patterns": "5 years",
        "quantum_states": "2 years"
      },
      "rights": [
        "Right to access",
        "Right to rectification", 
        "Right to erasure",
        "Right to data portability",
        "Right to object"
      ],
      "automated_decision_making": false,
      "profiling": false
    }
  
  cookie_policy.json: |
    {
      "essential_cookies": [
        {
          "name": "session_id",
          "purpose": "Session management",
          "duration": "Session"
        }
      ],
      "analytics_cookies": [],
      "marketing_cookies": [],
      "consent_required": true
    }

---
# Transfer Agreements ConfigMap  
apiVersion: v1
kind: ConfigMap
metadata:
  name: transfer-agreements-config
  namespace: quantum-consciousness
data:
  standard_contractual_clauses_2021.txt: |
    Standard Contractual Clauses for transfers of personal data to third countries
    pursuant to Regulation (EU) 2016/679 of the European Parliament and of the Council
    
    Module Two: Transfer controller to processor
    
    [Full SCC text would be included here in production]
  
  binding_corporate_rules.txt: |
    Binding Corporate Rules for Terragon Labs Global Data Transfers
    
    [Full BCR text would be included here in production]

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: adequacy-decisions-config
  namespace: quantum-consciousness
data:
  adequate_countries.json: |
    {
      "countries": [
        {"code": "US", "name": "United States", "framework": "Data Privacy Framework", "valid_until": "2025-12-31"},
        {"code": "CA", "name": "Canada", "framework": "PIPEDA", "valid_until": "2026-01-01"},
        {"code": "JP", "name": "Japan", "framework": "APPI", "valid_until": "2025-01-23"},
        {"code": "KR", "name": "South Korea", "framework": "PIPA", "valid_until": "2025-12-17"},
        {"code": "NZ", "name": "New Zealand", "framework": "Privacy Act 2020", "valid_until": "2026-02-28"},
        {"code": "UY", "name": "Uruguay", "framework": "LPDP", "valid_until": "2026-08-21"}
      ],
      "last_updated": "2025-08-25"
    }