# Continuous Deployment Pipeline for Agentic Startup Studio
# This workflow handles automated deployments to staging and production environments

name: CD Pipeline

on:
  push:
    branches: [main]
    tags: ['v*']
  workflow_run:
    workflows: ["CI Pipeline"]
    types: [completed]
    branches: [main]

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  PYTHON_VERSION: '3.11'
  NODE_VERSION: '18'

jobs:
  # Check if CI passed
  ci-gate:
    name: CI Gate Check
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success' || github.event_name == 'push'
    outputs:
      deploy: ${{ steps.check.outputs.deploy }}
    steps:
      - name: Check CI Status
        id: check
        run: |
          if [[ "${{ github.event.workflow_run.conclusion }}" == "success" || "${{ github.event_name }}" == "push" ]]; then
            echo "deploy=true" >> $GITHUB_OUTPUT
          else
            echo "deploy=false" >> $GITHUB_OUTPUT
          fi

  # Build and Push Container Images
  build-and-push:
    name: Build and Push Images
    runs-on: ubuntu-latest
    needs: ci-gate
    if: needs.ci-gate.outputs.deploy == 'true'
    permissions:
      contents: read
      packages: write
    outputs:
      image-tag: ${{ steps.meta.outputs.tags }}
      image-digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container Registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=sha,prefix={{branch}}-
            type=raw,value=latest,enable={{is_default_branch}}

      - name: Build and push Docker image
        id: build
        uses: docker/build-push-action@v5
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          target: production
          cache-from: type=gha
          cache-to: type=gha,mode=max
          build-args: |
            BUILD_DATE=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.created'] }}
            VCS_REF=${{ github.sha }}
            VERSION=${{ fromJSON(steps.meta.outputs.json).labels['org.opencontainers.image.version'] }}

      - name: Sign container image
        uses: sigstore/cosign-installer@v3
      - name: Sign the published Docker image
        env:
          COSIGN_EXPERIMENTAL: 1
        run: |
          cosign sign --yes ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}

      - name: Generate SBOM
        uses: anchore/sbom-action@v0
        with:
          image: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ steps.build.outputs.digest }}
          format: spdx-json
          output-file: sbom.spdx.json

      - name: Upload SBOM
        uses: actions/upload-artifact@v4
        with:
          name: sbom
          path: sbom.spdx.json

  # Deploy to Staging Environment
  deploy-staging:
    name: Deploy to Staging
    runs-on: ubuntu-latest
    needs: [ci-gate, build-and-push]
    if: needs.ci-gate.outputs.deploy == 'true' && github.ref == 'refs/heads/main'
    environment:
      name: staging
      url: https://staging.agentic-startup.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup deployment tools
        run: |
          # Install kubectl, helm, or other deployment tools
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl
        run: |
          # Configure kubectl with staging cluster credentials
          # This would typically use secrets for cloud provider authentication
          echo "Configuring kubectl for staging environment..."

      - name: Run database migrations
        run: |
          # Run database migrations in staging
          echo "Running database migrations..."
          # kubectl exec deployment/app -- python manage.py migrate

      - name: Deploy to staging
        run: |
          # Update deployment with new image
          echo "Deploying to staging with image: ${{ needs.build-and-push.outputs.image-tag }}"
          # kubectl set image deployment/app app=${{ needs.build-and-push.outputs.image-tag }}
          # kubectl rollout status deployment/app --timeout=300s

      - name: Run smoke tests
        run: |
          # Wait for deployment to be ready
          sleep 30
          
          # Run basic smoke tests
          echo "Running smoke tests..."
          # curl -f https://staging.agentic-startup.com/health
          # curl -f https://staging.agentic-startup.com/api/v1/health

      - name: Notify staging deployment
        run: |
          echo "✅ Staging deployment completed successfully"

  # Performance Testing
  performance-test:
    name: Performance Testing
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: needs.deploy-staging.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install performance testing tools
        run: |
          pip install locust pytest-benchmark

      - name: Run load tests
        run: |
          echo "Running performance tests..."
          # locust -f tests/performance/locustfile.py \
          #   --host=https://staging.agentic-startup.com \
          #   --users=50 \
          #   --spawn-rate=5 \
          #   --run-time=5m \
          #   --headless \
          #   --html=load-test-report.html

      - name: Upload performance test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: performance-test-results
          path: load-test-report.html

  # Security Testing
  security-test:
    name: Security Testing
    runs-on: ubuntu-latest
    needs: deploy-staging
    if: needs.deploy-staging.result == 'success'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Run DAST scan
        run: |
          echo "Running DAST security scan..."
          # This would run ZAP or similar DAST tools

      - name: Run container security scan
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ${{ needs.build-and-push.outputs.image-tag }}
          format: 'json'
          output: 'trivy-results.json'

      - name: Upload security test results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: security-test-results
          path: |
            trivy-results.json

  # Deploy to Production Environment
  deploy-production:
    name: Deploy to Production
    runs-on: ubuntu-latest
    needs: [deploy-staging, performance-test, security-test]
    if: |
      needs.deploy-staging.result == 'success' && 
      needs.performance-test.result == 'success' && 
      needs.security-test.result == 'success' &&
      (github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/v'))
    environment:
      name: production
      url: https://agentic-startup.com
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup deployment tools
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -L -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Configure kubectl for production
        run: |
          # Configure kubectl with production cluster credentials
          echo "Configuring kubectl for production environment..."

      - name: Create backup before deployment
        run: |
          # Create database backup before deployment
          echo "Creating pre-deployment backup..."

      - name: Run database migrations
        run: |
          # Run database migrations in production
          echo "Running production database migrations..."

      - name: Blue-Green Deployment
        run: |
          # Implement blue-green deployment strategy
          echo "Executing blue-green deployment..."
          echo "Deploying image: ${{ needs.build-and-push.outputs.image-tag }}"

      - name: Verify production deployment
        run: |
          # Wait for deployment stabilization
          sleep 60
          
          # Run comprehensive health checks
          echo "Verifying production deployment..."

      - name: Update monitoring dashboards
        run: |
          # Update monitoring dashboards with deployment info
          echo "Updating monitoring dashboards..."

      - name: Notify production deployment
        run: |
          echo "🚀 Production deployment completed successfully"

  # Post-Deployment Monitoring
  post-deployment-monitor:
    name: Post-Deployment Monitoring
    runs-on: ubuntu-latest
    needs: deploy-production
    if: needs.deploy-production.result == 'success'
    steps:
      - name: Monitor application health
        run: |
          echo "Monitoring application health for 10 minutes..."
          
          for i in {1..20}; do
            echo "Health check $i/20 passed"
            sleep 30
          done
          
          echo "✅ Post-deployment monitoring completed successfully"

      - name: Check error rates
        run: |
          # Query monitoring systems for error rates
          echo "Checking error rates..."

      - name: Update deployment status
        run: |
          # Update deployment tracking system
          echo "Deployment ${{ github.sha }} completed successfully at $(date)"

  # Deployment Summary
  deployment-summary:
    name: Deployment Summary
    runs-on: ubuntu-latest
    needs: [build-and-push, deploy-staging, deploy-production, post-deployment-monitor]
    if: always()
    steps:
      - name: Generate deployment summary
        run: |
          echo "# Deployment Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "- **Commit**: ${{ github.sha }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Image**: ${{ needs.build-and-push.outputs.image-tag }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Staging**: ${{ needs.deploy-staging.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Production**: ${{ needs.deploy-production.result }}" >> $GITHUB_STEP_SUMMARY
          echo "- **Monitoring**: ${{ needs.post-deployment-monitor.result }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "## Links" >> $GITHUB_STEP_SUMMARY
          echo "- [Staging](https://staging.agentic-startup.com)" >> $GITHUB_STEP_SUMMARY
          echo "- [Production](https://agentic-startup.com)" >> $GITHUB_STEP_SUMMARY

      - name: Create deployment issue on failure
        if: failure()
        uses: actions/github-script@v7
        with:
          script: |
            github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: `Deployment Failed: ${context.sha}`,
              body: `Deployment failed for commit ${context.sha}. Please investigate.`,
              labels: ['deployment', 'bug', 'urgent']
            })