name: CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  validate-template:
    runs-on: ubuntu-latest
    name: Validate Cookiecutter Template

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install cookiecutter pyyaml

    - name: Validate cookiecutter.json
      run: |
        python -c "import json; json.load(open('cookiecutter.json'))"
        echo "✓ cookiecutter.json is valid JSON"

    - name: Run cookiecutter template tests
      run: |
        if [ -f "test_cookiecutter_config.py" ]; then
          python test_cookiecutter_config.py
        fi

    - name: Test cookiecutter template generation  
      run: |
        # Test template generation with default values
        cookiecutter . --no-input --output-dir /tmp/test-output
        echo "✓ Template generation successful"

    - name: Validate generated project structure
      run: |
        # Basic validation that cookiecutter created output
        if [ -d "/tmp/test-output" ]; then
          echo "✓ Template output directory created"
          ls -la /tmp/test-output/
        else
          echo "❌ Template generation failed"
          exit 1
        fi

  lint-and-check:
    runs-on: ubuntu-latest
    name: Lint and Check Files

    steps:
    - name: Checkout repository  
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install linting tools
      run: |
        python -m pip install --upgrade pip
        pip install yamllint

    - name: Lint YAML files
      run: |
        find . -name "*.yml" -o -name "*.yaml" | xargs yamllint -d relaxed

    - name: Check for broken links in README
      run: |
        if [ -f "test_readme_badges.py" ]; then
          python test_readme_badges.py
        fi

    - name: Validate CI workflow
      run: |
        if [ -f "test_ci_workflow.py" ]; then
          python test_ci_workflow.py
        fi

    - name: Check file permissions
      run: |
        # Ensure no executable files are accidentally committed
        find . -type f -executable ! -path "./.git/*" ! -name "*.sh" | head -10